import { PERMISSIONS } from "./permission";
import { UserRole } from "../models/User";

export const ROLE_DEFAULT_PERMISSIONS: Record<UserRole, string[]> = {
  owner: Object.values(PERMISSIONS), // all permissions
  manager: [
    PERMISSIONS.MENU_VIEW,
    PERMISSIONS.MENU_CREATE,
    PERMISSIONS.MENU_UPDATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.INGREDIENT_VIEW,
    PERMISSIONS.INGRDIENT_CREATE,
    PERMISSIONS.INGREDIENT_UPDATE,
    PERMISSIONS.INGREDIENT_DELETE
  ],
  chef: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.INGREDIENT_VIEW,
    PERMISSIONS.MENU_UPDATE,
    PERMISSIONS.MENU_VIEW
  ],
  waiter: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.TABLE_UPDATE,
    PERMISSIONS.INGREDIENT_VIEW,
    PERMISSIONS.MENU_VIEW,
  ],
};
